#ifndef MQTT_RC_H
#define MQTT_TC_H

enum mqtt_connection_rc_t
{
	MQTT_CONNECTION_ACCEPTED = 0,
	MQTT_UNACCEPTABLE_PROTOCOL_VERSION = 1,
	MQTT_IDENTIFIER_REJECTED = 2,
	MQTT_SERVER_UNAVAILABLE = 3,
	MQTT_BAD_CREDENTIALS = 4,
	MQTT_NOT_AUTHORIZED = 5
};

enum mqtt_suback_rc_t
{
	SUBACK_MAX_QOS_0 = 0x00,
	SUBACK_MAX_Q0S_1 = 0x01,
	SUBACK_MAX_QOS_2 = 0x02,
	SUBACK_FAILURE = 0x80
};

#endif
